server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /fivegourp_backstage

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.121/wu?characterEncoding=UTF-8
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  redis:
    host: 192.168.1.104
    port: 6379
    jedis:
      pool:
        max-idle: 300
        max-active: 600
        max-wait: 300
  data:
    mongodb:
      host: 192.168.1.104
      port: 27017
      database: 1801a
    solr:
      host: http://192.168.1.137:8080/solr/mycore
  rabbitmq:
    host: 192.168.1.113
    port: 5672
    username: wchen92
    password: wchen92
